---
fail_fast: true
default_install_hook_types: [pre-commit, commit-msg]
repos:
  # Lint the Commit messages
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Lint the Code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        types_or: [ python ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.400
    hooks:
    - id: pyright
